// File: app/lib/apiPassenger.ts

import { apiGet, apiPost, apiPut, apiDelete } from './apiClient';
import { Passenger } from '../types/Passenger';

const BASE_PATH = '/api/passengers';

/**
 * Fetches all passenger records.
 * @returns A promise that resolves to an array of Passenger objects.
 */
export async function getAllPassengers(): Promise<Passenger[]> {
  return apiGet<Passenger[]>(BASE_PATH);
}

/**
 * Fetches a single passenger record by its ID.
 * @param id The PassengerID.
 * @returns A promise that resolves to a Passenger object.
 */
export async function getPassengerById(id: string): Promise<Passenger> {
  return apiGet<Passenger>(`${BASE_PATH}/${id}`);
}

/**
 * Creates a new passenger record.
 * @param passenger The passenger data to create (passengerID will be auto-generated by backend).
 * @returns A promise that resolves to the created Passenger object.
 */
export async function createPassenger(passenger: Omit<Passenger, 'passengerID'>): Promise<Passenger> {
  return apiPost<Passenger>(BASE_PATH, passenger);
}

/**
 * Updates an existing passenger record.
 * @param id The PassengerID.
 * @param passenger Partial passenger data to update.
 * @returns A promise that resolves to the updated Passenger object.
 */
export async function updatePassenger(id: string, passenger: Partial<Passenger>): Promise<Passenger> {
  return apiPut<Passenger>(`${BASE_PATH}/${id}`, passenger);
}

/**
 * Deletes a passenger record.
 * @param id The PassengerID.
 */
export async function deletePassenger(id: string): Promise<void> {
  return apiDelete<void>(`${BASE_PATH}/${id}`);
}

