// File: app/lib/apiTicket.ts

import { apiGet, apiPost, apiPut, apiDelete } from './apiClient';
import { Ticket } from '../types/Ticket';

const BASE_PATH = '/api/tickets';

/**
 * Fetches all ticket records.
 * @returns A promise that resolves to an array of Ticket objects.
 */
export async function getAllTickets(): Promise<Ticket[]> {
  return apiGet<Ticket[]>(BASE_PATH);
}

/**
 * Fetches a single ticket record by its ID.
 * @param id The TicketID.
 * @returns A promise that resolves to a Ticket object.
 */
export async function getTicketById(id: string): Promise<Ticket> {
  return apiGet<Ticket>(`${BASE_PATH}/${id}`);
}

/**
 * Fetches all tickets for a specific passenger.
 * @param passengerId The PassengerID.
 * @returns A promise that resolves to an array of Ticket objects.
 */
export async function getTicketsByPassengerId(passengerId: string): Promise<Ticket[]> {
  return apiGet<Ticket[]>(`/api/passengers/${passengerId}/tickets`);
}

/**
 * Creates a new ticket record.
 * @param ticket The ticket data to create (ticketID will be auto-generated by backend).
 * @returns A promise that resolves to the created Ticket object.
 */
export async function createTicket(ticket: Omit<Ticket, 'ticketID'>): Promise<Ticket> {
  return apiPost<Ticket>(BASE_PATH, ticket);
}

/**
 * Updates an existing ticket record.
 * @param id The TicketID.
 * @param ticket Partial ticket data to update.
 * @returns A promise that resolves to the updated Ticket object.
 */
export async function updateTicket(id: string, ticket: Partial<Ticket>): Promise<Ticket> {
  return apiPut<Ticket>(`${BASE_PATH}/${id}`, ticket);
}

/**
 * Deletes a ticket record.
 * @param id The TicketID.
 */
export async function deleteTicket(id: string): Promise<void> {
  return apiDelete<void>(`${BASE_PATH}/${id}`);
}