'use client';

import EntityNewPage, { FieldConfig } from '@/app/_components/EntityNewPage';

const fields: FieldConfig[] = [
  // LuggageID is auto-generated by the backend
  { name: 'ticketID', label: 'Ticket ID', required: true, placeholder: 'TI00001' },
  { name: 'weight', label: 'Weight (kg)', required: true, type: 'number', placeholder: '23.5' },
  { name: 'status', label: 'Status', required: true, placeholder: 'Checked-In' },
];

export default function NewLuggagePage() {
  return (
    <EntityNewPage
      title="New Luggage Record"
      apiPath="/api/luggages"
      backHref="/luggage"
      fields={fields}
    />
  );
}