'use client';

import EntityNewPage, { FieldConfig } from '@/app/_components/EntityNewPage';

const fields: FieldConfig[] = [
  // FlightID is auto-generated by the backend
  { name: 'flightNum', label: 'Flight Number', required: true, placeholder: 'VN123' },
  { name: 'aircraftID', label: 'Aircraft ID', required: true, placeholder: 'AC001' },
  { name: 'origin', label: 'Origin Airport', required: true, placeholder: 'Hanoi' },
  { name: 'destination', label: 'Destination Airport', required: true, placeholder: 'Ho Chi Minh' },
  { name: 'departureTime', label: 'Departure Time', required: true, type: 'date' },
  { name: 'arrivalTime', label: 'Arrival Time', required: true, type: 'date' },
  { name: 'status', label: 'Status', required: true, placeholder: 'On Time, Delayed, etc.' },
];

export default function NewFlightPage() {
  return (
    <EntityNewPage
      title="New Flight"
      apiPath="/api/flights"
      backHref="/flights"
      fields={fields}
    />
  );
}