'use client';

import EntityNewPage, { FieldConfig } from '@/app/_components/EntityNewPage';

const fields: FieldConfig[] = [
  // PassID is auto-generated by the backend (UUID)
  { name: 'ticketID', label: 'Ticket ID', required: true, placeholder: 'TI00001' },
  { name: 'flightID', label: 'Flight ID', required: true, placeholder: 'FL00001' },
  { name: 'gateNum', label: 'Gate Number', required: true, placeholder: 'A15' },
  { name: 'seat', label: 'Seat', required: true, placeholder: '1A' },
  { name: 'boardingTime', label: 'Boarding Time', required: true, type: 'date' },
  { name: 'status', label: 'Status', required: true, placeholder: 'Boarded' },
];

export default function NewBoardingPage() {
  return (
    <EntityNewPage
      title="New Boarding Pass"
      apiPath="/api/boardings"
      backHref="/boardings"
      fields={fields}
    />
  );
}